val javaVersion = "11"
val kodeinVersion  = "7.2.0"
val kotlinVersion = "1.4.21"
val kotlinCoroutineVersion = "1.4.2"
val functionsFrameworkApiVersion = "1.0.3"
val javaFunctionInvokerVersion = "1.0.1"
val gsonVersion = "2.8.5"
val jUnitVersion = "5.4.2"